spring.application.name=tradeflow-backend

spring.datasource.url=jdbc:mysql://localhost:3306/tradeflowdb
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.springframework.security=DEBUG


resend.api.key=re_gdRhEbbM_ByS9JxBEpELeFYt21USfWkMM

app.base-url=http://localhost:8080

app.email.from=TradeFlow <onboarding@resend.dev>

jwt.secret=ReplaceThisWithYourVeryLongSecretKeyAtLeast32CharactersLong123456789
jwt.expiration=86400000


####################################
# Angel One
####################################

angelone.api.key=YOUR_API_KEY
angelone.client.code=YOUR_CLIENT_CODE
angelone.pin=YOUR_PIN
angelone.totp.secret=YOUR_TOTP_SECRET
angelone.base.url=https://apiconnect.angelone.in